---
title: "Data Dictionary"
author: "Jennifer Collister"
date: "11/03/2020"
output: 
  word_document:
      reference_docx: "K:/TEU/APOE on Dementia/RMarkdownLandscape.docx"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(knitr)
library(dataMeta)
library(readxl)
library(devtools)
library(dplyr)

install_local("K:\\TEU\\Code Repository\\dataMetaFork")

data <- readRDS(file="K:\\TEU\\APOE on Dementia\\Data Management\\R_Dataframes_TLA\\38358\\Organised\\Hypertension\\Neo\\HTN_excl.rds")

dictpath <- "K:\\TEU\\APOE on Dementia\\Data Management\\DataDictionary\\DataDictionary.xlsx"

```

# Core analysis


```{r datameta, include=TRUE, echo=FALSE}

core <- data[,c("ID", "evidenceHTN_", "aware_", "treated_", "controlled_", "ethnicity", "age", "gender", "ISCED", "BMIcat", "BMI", "recdate")]

core_linker <- build_linker(core, master_dictionary=dictpath)

core_dict <- build_dict(my.data=core, linker=core_linker, option_description=NULL, prompt_varopts=FALSE, na.rm=TRUE)

kable(core_dict)

core_desc = "The variables required for the core analysis"

coredata <- incorporate_attr(my.data=core, data.dictionary=core_dict, main_string=core_desc)

```


# Expanded analysis


```{r extradict, include=TRUE, echo=FALSE}

extra <- data[,c("ID", 
                 "GroupB", "GroupC", 
                 "BirthCountryIncomeLevel", "income", "townsend_depind", "employment", "shiftwork",
                 "Smo_Status", "alc_binge_", "METs_over150_", "PhA_METsWkAllAct", "Sle_Duration",
                 "mean_reacttime",
                 "HTNdx_duration", "HTNdx_severity",
                 "FamilyHist_CVD_", 
                 "WaistCirc"
                 )]

extra_linker <- build_linker(extra, master_dictionary=dictpath)

extra_dict <- build_dict(my.data=extra, linker=extra_linker, option_description=NULL, prompt_varopts=FALSE, na.rm=TRUE)

kable(extra_dict)

extra_desc = "The variables required for the core analysis"

extradata <- incorporate_attr(my.data=extra, data.dictionary=extra_dict, main_string=extra_desc)

```





