data:
 received: "K:/TEU/UKB33952_Data/Data_Downloads/v2_TLAtables"
 derived: "Data/Derived"
 analysed: "Data/Analysed"
 prs: "K:/TEU/UKB_Genetic_Data/bmrc-ukb-repo/prs/htn-evangelou2018/outputs"
cleaning:
 withdrawals: "K:/TEU/UKB33952_Data/Data_Downloads/Withdrawals/WithdrawnIDs.csv"
 coding: "K:/TEU/UKB33952_Data/Data_Dictionary/Mappings"
 mapping: "Data/Mappings"
outputs:
 figures: "Scripts/Stats_Analysis/RMarkdown/Figures"
 flowcharts: "Scripts/Stats_Analysis/Flowcharts"
functions: "Scripts/Stats_Analysis/JCfunctions.R"
scripts:
 cleaning: "Scripts/Data_Management/Scripts_Cleaning"
 processing: "Scripts/Data_Management/Scripts_Processing"

