data:
 database: "K:/TEU/UKB33952_Data/Data_Downloads/V3_database_duckdb0.2.1/ukb_v3.db"
 portal:
  HES: "K:/TEU/UKB33952_Data/Data_Portal/HES_diagnoses/20210129"
  deaths: "K:/TEU/UKB33952_Data/Data_Portal/Death_Registry/20210129"
 derived: "Data/Derived"
 dictionary: "Data/Data_Dictionary"
 prs: "Data/PRS"
cleaning:
 withdrawals: "K:/TEU/UKB33952_Data/Data_Downloads/Withdrawals/w33952_20210201.csv"
 renaming: "K:/TEU/UKB33952_Data/Data_Dictionary/Renaming_List_UPDATE_Sep2020_TEU.csv"
 coding: "K:/TEU/UKB33952_Data/Data_Dictionary/Mappings/Encoding_files"
 mapping: "Data/Mappings"
outputs:
 figures: "Scripts/Stats_Analysis/RMarkdown/Figures"
 flowcharts: "Scripts/Stats_Analysis/Flowcharts"
explore: "K:/TEU/TEU_Members/Xiaonan_Liu/Projects/PRSonCholstrl/Scripts/Initial_Exploration/"
functions:
 JC: "Scripts/Stats_Analysis/JCfunctions.R"
 general: "K:/TEU/TEU_Members/Xiaonan_Liu/Projects/PRSonCholstrl/Scripts/Stats_Analysis/General_Func/JCfunctions_XL.R"
 flowchart: "K:/TEU/TEU_Members/Xiaonan_Liu/Projects/PRSonCholstrl/Scripts/Stats_Analysis/General_Func/FlowChart_pop.R"
 descriptive: "K:/TEU/TEU_Members/Xiaonan_Liu/Projects/PRSonCholstrl/Scripts/Stats_Analysis/General_Func/DescrpStats.R"
scripts:
 cleaning: "Scripts/Data_Management/Scripts_Cleaning"
 processing: "Scripts/Data_Management/Scripts_Processing"

