data:
 received: "K:/TEU/UKB33952_Data/Data_Downloads/v1_TLAtables/"
 derived: "Data/Derived/"
 analysed: "Data/Analysed/"
 prs: "K:/TEU/UKB_Genetic_Data/bmrc-ukb-repo/prs/htn-evangelou2018/outputs/"
cleaning:
 withdrawals: "K:/TEU/UKB33952_Data/Data_Downloads/Withdrawals/WithdrawnIDs.csv"
 coding: "K:/TEU/UKB33952_Data/Data_Dictionary/Mappings/"
 mapping: "Data/Mappings/"
outputs:
 figures: "Stats_Analysis/Figures/"
 flowcharts: "Stats_Analysis/Flowcharts/"
functions: "Stats_Analysis/JCfunctions.R"
scripts:
 cleaning: "Data_Management/Scripts_Cleaning/"
 processing: "Data_Management/Scripts_Processing/"

