---
title: "Exploration of correlation between comorbidities and removal of occupation to see if associated with physical activity"
author: "Jennifer Collister"
date: "24/04/2020"
output: 
  word_document:
      reference_docx: "K:/TEU/APOE on Dementia/RMarkdownStyle.docx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(knitr)
library(DiagrammeR)
library(DiagrammeRsvg)
library(magrittr)
library(svglite)
library(rsvg)
library(png)

source("K:/TEU/APOE on Dementia/Statistical Analysis/JCfunctions.R")
options(knitr.kable.NA='')

data <- readRDS(file="K:\\TEU\\APOE on Dementia\\Data Management\\R_Dataframes_TLA\\38358\\Organised\\Hypertension\\Neo\\HTN_excl.rds")


# Comorbidities of interest
comorbs <- readRDS("K:\\TEU\\APOE on Dementia\\Data Management\\R_Dataframes_TLA\\38358\\Organised\\Hypertension\\Neo\\VI_HTNcomorb.rds")
colnames(comorbs) <- c("ID", paste0("VI_", colnames(comorbs)[-1]))
print(colnames(comorbs)[-1])
comorbs_raw <- c("VI_afib_or_aflutter", "VI_CVD", "VI_diabetes", "VI_asthma_or_COPD", "VI_migraine", "VI_epilepsy",
                 "VI_anxiety_or_stress", "VI_depression_or_bipolar")
comorbs_string <- paste0(comorbs_raw, "_")

# In this analysis, we want to consider two subsets: all hypertensives and all treated individuals
hypertensives <- data[data$evidenceHTN==TRUE & !is.na(data$evidenceHTN),]
treated <- data[data$treated==TRUE & !is.na(data$treated),]

# Among the treated, those who did not list any HTN meds in VI are assumed to be taking unlisted meds
treated$antiHTNmedsno <- factor(treated$antiHTNmedsno, levels=c("1", "2", ">=3", "0"),
                                labels=c("1", "2", ">=3",  "Medication list unavailable"))

pretty_names <- list(agegrp = "Age group",
                     gender = "Gender",
                     ethnicity = "Ethnicity",
                     genWhiteBrit = "Genetically categorised as White British",
                     BMIcat = "BMI (categorical)",
                     Smo_Status = "Smoking status",
                     weekly_alcunits = "Alcohol units per week",
                     weekly_alccat = "Alcohol units per week (categorical)",
                     PhA_METsWkAllAct = "Weekly physical activity, in METs",
                     METs_over1200 = "Sufficient physical activity",
                     townsend_quint = "Townsend Deprivation Index, quintiles",
                     income = "Household Income, GBP",
                     employment = "Occupation type",
                     ISCED = "Highest level of education (ISCED)",
                     BirthCountryIncomeLevel = "Country of birth, by income level",
                     countryResidence = "UK country of residence",
                     BowelCancerScreening = "Ever screened for bowel cancer",
                     HTNdx_durcat = "Duration of hypertension (categorical)",
                     antiHTNmedsno = "Number of antihypertensive medications",
                     FamilyHist_CVD_ = "Family history of CVD",
                     comorbNumber_ = "No. of comorbidities",
                     VI_afib_or_aflutter_ = "Arrhythmia (afib/flutter)",
                     VI_anxiety_or_stress_ = "Anxiety",
                     VI_asthma_or_COPD_ = "Asthma or COPD",
                     VI_depression_or_bipolar_ = "Depression",
                     VI_diabetes_ = "Diabetes",
                     VI_epilepsy_ = "Epilepsy",
                     VI_CVD_ = "Cardiovascular disease",
                     VI_migraine_ = "Migraines",
                     VI_substance_use_ = "Substance use"
                     )
prettyfunc <- function(x){
  if(x %in% names(pretty_names)){
     return(pretty_names[[x]])
  } else {
    return(x)
  }
}
```



```{r explorequadage, include=FALSE, echo=FALSE}
# 
# treated$age2 <- (treated$c40_age)^2
# 
# varlist1=c("agegrp", "gender", "ethnicity",
#           "townsend_quint", "income", "ISCED", "BirthCountryIncomeLevel", "countryResidence",
#           "BMIcat", "Smo_Status", "weekly_alccat", "METS_over1200",
#           "antiHTNmedsno",  "FamilyHist_CVD_",
#           "comorbNumber_", comorbs_string,
#            "BowelCancerScreening")
# varlist2=c("agegrp", "gender", "ethnicity",
#           "townsend_quint", "ISCED", "BirthCountryIncomeLevel", "countryResidence",
#           "BMIcat", "Smo_Status", "weekly_alccat", "METS_over1200",
#           "antiHTNmedsno",  "FamilyHist_CVD_",
#           "comorbNumber_", comorbs_string,
#            "BowelCancerScreening")
# model1 <- glm(formula=paste0("controlled ~ ",paste0(varlist1, collapse="+")), data=treated, family="binomial")
# model2 <- glm(formula=paste0("controlled ~ ",paste0(varlist2, collapse="+")), data=treated, family="binomial")
# anova(model1, model2, test="Chisq")
# 
# # printlogresults(model)
# 
# model1 <- glm(controlled ~ c40_age, data=treated, family="binomial")
# model2 <- glm(controlled ~ c40_age + age2, data=treated, family="binomial")
# anova(model1, model2, test="Chisq")
```

```{r correlation_deprivation, include=FALSE, echo=FALSE}
# library(corrplot)
# 
# ses <- treated[,c("townsend_depind", "townsend_quint", "income", "ISCED", "employment")]
# ses$townsend_quint <- as.numeric(unclass(ses$townsend_quint))
# ses$income <- as.numeric(unclass(ses$income))
# ses$ISCED <- as.numeric(unclass(ses$ISCED))
# ses$employment <- as.numeric(unclass(ses$employment))
# 
# res <- cor(ses, method = "spearman", use = "complete.obs")
# res
# corrplot(res, type = "upper", order = "hclust", 
#          tl.col = "black", tl.srt = 45)
# 
# pairs(ses)

```

# Correlation between individual comorbidities

```{r correlation_comorbs, include=TRUE, echo=FALSE}
library(corrplot)

comorbs <- treated[,c("VI_afib_or_aflutter_", "VI_CVD_", "VI_diabetes_", "VI_asthma_or_COPD_", "VI_migraine_", "VI_epilepsy_", "VI_anxiety_or_stress_", "VI_depression_or_bipolar_")]
for(col in colnames(comorbs)){
  comorbs[[col]] <- as.numeric(unclass(comorbs[[col]]))
}

res <- cor(comorbs, method = "spearman", use = "complete.obs")
res
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)


```

```{r METthreshold, include=FALSE, echo=FALSE, results='asis'}
# hist(treated$PhA_METsWkAllAct, main="Histogram of total weekly MET minutes among treated population",
#      xlab="Total weekly MET minutes", cex.main=0.8)
# hist(treated$PhA_METsWkAllAct[treated$PhA_METsWkAllAct<5000], 
#      main="Close-up of 0-5000 MET minutes region of previous histogram",
#      xlab="Total weekly MET minutes up to 5000", cex.main=0.8)
# 
# # WHO thresholds: recommended 600-1200 MET minutes per week
# treated$METs_over600 <- dplyr::case_when(
#   treated$PhA_METsWkAllAct > 600 & !is.na(treated$PhA_METsWkAllAct) ~ "High (METs > 600)",
#   treated$PhA_METsWkAllAct <= 600 & !is.na(treated$PhA_METsWkAllAct) ~ "Low (METs <= 600)",
#   TRUE ~ "Unknown")
# treated$METs_over600 <- factor(treated$METs_over600, 
#                                 levels=c("High (METs > 600)", "Low (METs <= 600)", "Unknown"))
# 
# # New recommendations show most health gains occur at 3000-4000 MET minutes per week
# treated$METs_over3000 <- dplyr::case_when(
#   treated$PhA_METsWkAllAct > 3000 & !is.na(treated$PhA_METsWkAllAct) ~ "High (METs > 3000)",
#   treated$PhA_METsWkAllAct <= 3000 & !is.na(treated$PhA_METsWkAllAct) ~ "Low (METs <= 3000)",
#   TRUE ~ "Unknown")
# treated$METs_over3000 <- factor(treated$METs_over3000, 
#                                 levels=c("High (METs > 3000)", "Low (METs <= 3000)", "Unknown"))
# 
# treated$METs_over4000 <- dplyr::case_when(
#   treated$PhA_METsWkAllAct > 4000 & !is.na(treated$PhA_METsWkAllAct) ~ "High (METs > 4000)",
#   treated$PhA_METsWkAllAct <= 4000 & !is.na(treated$PhA_METsWkAllAct) ~ "Low (METs <= 4000)",
#   TRUE ~ "Unknown")
# treated$METs_over4000 <- factor(treated$METs_over4000, 
#                                 levels=c("High (METs > 4000)", "Low (METs <= 4000)", "Unknown"))
# 
# METSvars <- c("METs_over600", "METs_over1200", "METs_over3000", "METs_over4000")
# for(var in METSvars){
#   formula <- paste0("controlled ~ agegrp + gender + ", var)
#   print(kable(printlogresults(glm(formula=formula, data=treated, family="binomial"))))
# }
 
```

```{r crosstab, include=FALSE, echo=FALSE}

# table(treated$comorbNumber, treated$VI_diabetes, useNA='ifany')
# 
# kable(printlogresults(glm(controlled ~ agegrp + gender + VI_diabetes_, data=treated, family="binomial")))
# kable(printlogresults(glm(controlled ~ agegrp + gender + comorbNumber_, data=treated, family="binomial")))
# 
# kable(printlogresults(glm(controlled ~ agegrp + gender + VI_diabetes + comorbNumber_, 
#                           data=treated, family="binomial")))

```

# Drop employment out to see if it's associated with physical activity

```{r table3_noemployment, include=TRUE, echo=FALSE}

varlist=c("agegrp", "gender", "eth_group",
          "townsend_quint", "income", "ISCED", "BirthCountryIncomeLevel", "countryResidence",
          "BMIcat", "Smo_Status", "weekly_alccat", "METs_over1200",
          "antiHTNmedsno",  "FamilyHist_CVD_",
          "comorbNumber_", "VI_CVD_",
           "BowelCancerScreening")

n <- data.frame(descriptivetable(df=treated, 
                         varlist=varlist,
                         contavg='median',
                         pretty_names=pretty_names),
                stringsAsFactors = FALSE)

adj <- regressiontable(df=treated, outcome="controlled", varlist=varlist, 
                       regresstype="adjusted", adjvarlist=c("agegrp", "gender"))
multi <- regressiontable(df=treated, outcome="controlled", varlist=varlist, 
                         regresstype="multivariable")
tab3 <- merge(adj, multi, by=c("IDcol", "Coefficient", "Level"), sort=FALSE)
# Add n column
tab3$n <- n$n

# Hide "unanswered"/"unknown"/"do not know" categories
tab3 <- tab3[-which(tab3$Level %in% c("Unknown", "Unanswered", "Do not know", "Prefer not to answer")),]
rownames(tab3) <- NULL

tab3 <- tab3[,c("Coefficient", "Level", "n", "OR.x", "95% CI.x", "p.x", "OR.y", "95% CI.y", "p.y")]
tab3 <- rbind(c("Coefficient", "Level", "n", "OR", "95% CI", "p", "OR", "95% CI", "p"),
              tab3)
colnames(tab3) <- c("","","", "Age- and sex-adjusted", "", "", "Fully adjusted", "", "")


tab3[,1] <- sapply(tab3[,1], prettyfunc)
kable(tab3, caption="Logistic regressions of various factors against hypertension control status, odds ratios are for successful BP control.")

```

