---
title: "Investigating gender HR"
author: "Jennifer Collister"
date: "25/02/2020"
output: 
  word_document:
      reference_docx: "K:/TEU/TEU Guides/TEU_DocStyle_Rmd_2020.dotx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(survival)
library(survminer)
library(lmtest)
library(kableExtra)
library(knitr)
library(timereg)
library(epitools)
library(tab)
library(popEpi)

library(yaml)
library(here)

# Specify the markdown format for knitr tables, otherwise they're not compatible with kableExtra
options(knitr.kable.NA='', knitr.table.format = "markdown")
options(kableExtra.auto_format = FALSE)
# Set the root directory to the project directory (otherwise knitr works in the directory of the Rmd file by default)
knitr::opts_knit$set(root.dir = here::here())

# Load the project config file for filepaths etc
config = yaml.load_file(here::here("./config.yml"))

# Load data
data <- readRDS(file=paste0(config$analysisdata$apoe, "apoe_excl.rds"))

source("K:/TEU/APOE on Dementia/Statistical_Analysis/JCfunctions.R")

# Exclude individuals below the age of 60
data <- data[data$age>=60,]
```


```{r test, include=TRUE, echo=FALSE, results='asis'}
for(carrier in c(TRUE, FALSE)){
  tab1 <- table(data$controlled_[data$e4carrier==carrier], data$gender[data$e4carrier==carrier])

  tab2 <- table(data$controlled_[data$e4carrier==carrier & data$dementia_status==TRUE], data$gender[data$e4carrier==carrier & data$dementia_status==TRUE])
  
  tabpct <- round(100*tab2/tab1,2)
  
  prettytab <- tab2
  for(i in c(1:2)){
    for(j in c(1:2)){
      prettytab[i,j] <- paste0(tab2[i,j], "/", tab1[i,j], " (", tabpct[i,j], "%)")
    }
  }
  print(kable(prettytab, caption=paste0("Among the treated population with e4 carrier = ", carrier, " the number of dementia cases out of total individuals in each category is:")))
  
}


```

# Combine carriers and non-carriers, regress e4 carrier status, control status and interaction term

```{r genderHR, include=TRUE, echo=FALSE}

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + gender + e4carrier_ + controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated),])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, gender, e4 carrier status and control status among participants who are taking BP medication, n=", model1$n))

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + gender + e4carrier_ * controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated),])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, gender, e4 carrier status and control status among participants who are taking BP medication, with interaction term, n=", model1$n))



```


# Combine carriers and non-carriers, regress e4 carrier status, control status and interaction term, stratified by sex

```{r stratifygender, include=TRUE, echo=FALSE}

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + e4carrier_ + controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated) & data$gender=="Female",])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, e4 carrier status and control status among females who are taking BP medication, n=", model1$n))

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + e4carrier_ * controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated) & data$gender=="Female",])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, e4 carrier status and control status among females who are taking BP medication, with interaction term, n=", model1$n))

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + e4carrier_ + controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated) & data$gender=="Male",])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, e4 carrier status and control status among males who are taking BP medication, n=", model1$n))

model1 <- coxph(Surv(time_to_dementia, dementia_status) ~ age + e4carrier_ * controlled_, 
                data=data[data$treated==TRUE & !is.na(data$treated) & data$gender=="Male",])
kable(printcoxresults(model1), 
      caption=paste0("Cox regression of age, e4 carrier status and control status among males who are taking BP medication, with interaction term, n=", model1$n))


```



